# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lex Chen\Desktop\datafram_test\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1211, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.COM_PORTS = QtWidgets.QComboBox(self.groupBox_5)
        self.COM_PORTS.setObjectName("COM_PORTS")
        self.horizontalLayout_3.addWidget(self.COM_PORTS)
        self.refreshComPorts = QtWidgets.QCommandLinkButton(self.groupBox_5)
        self.refreshComPorts.setMaximumSize(QtCore.QSize(80, 16777215))
        self.refreshComPorts.setObjectName("refreshComPorts")
        self.horizontalLayout_3.addWidget(self.refreshComPorts)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.BAUDRATES = QtWidgets.QComboBox(self.groupBox_5)
        self.BAUDRATES.setEditable(True)
        self.BAUDRATES.setObjectName("BAUDRATES")
        self.horizontalLayout_3.addWidget(self.BAUDRATES)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.VERIFY_BITS = QtWidgets.QComboBox(self.groupBox_5)
        self.VERIFY_BITS.setObjectName("VERIFY_BITS")
        self.horizontalLayout_3.addWidget(self.VERIFY_BITS)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.DATA_BITS = QtWidgets.QComboBox(self.groupBox_5)
        self.DATA_BITS.setObjectName("DATA_BITS")
        self.horizontalLayout_3.addWidget(self.DATA_BITS)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.STOP_BITS = QtWidgets.QComboBox(self.groupBox_5)
        self.STOP_BITS.setObjectName("STOP_BITS")
        self.horizontalLayout_3.addWidget(self.STOP_BITS)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.FLOW_CONTROLS = QtWidgets.QComboBox(self.groupBox_5)
        self.FLOW_CONTROLS.setObjectName("FLOW_CONTROLS")
        self.horizontalLayout_3.addWidget(self.FLOW_CONTROLS)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.openComPortBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.openComPortBtn.setObjectName("openComPortBtn")
        self.horizontalLayout_3.addWidget(self.openComPortBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.logTextEdit.setObjectName("logTextEdit")
        self.horizontalLayout_4.addWidget(self.logTextEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RCV_MODE_ASCII = QtWidgets.QRadioButton(self.groupBox_2)
        self.RCV_MODE_ASCII.setObjectName("RCV_MODE_ASCII")
        self.horizontalLayout_5.addWidget(self.RCV_MODE_ASCII)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.RCV_MODE_HEX = QtWidgets.QRadioButton(self.groupBox_2)
        self.RCV_MODE_HEX.setObjectName("RCV_MODE_HEX")
        self.horizontalLayout_5.addWidget(self.RCV_MODE_HEX)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.RCV_CHG_LINE = QtWidgets.QCheckBox(self.groupBox_2)
        self.RCV_CHG_LINE.setObjectName("RCV_CHG_LINE")
        self.horizontalLayout_5.addWidget(self.RCV_CHG_LINE)
        self.RCV_OFF_DISPLAY = QtWidgets.QCheckBox(self.groupBox_2)
        self.RCV_OFF_DISPLAY.setObjectName("RCV_OFF_DISPLAY")
        self.horizontalLayout_5.addWidget(self.RCV_OFF_DISPLAY)
        self.RCV_SAV_FILE = QtWidgets.QCheckBox(self.groupBox_2)
        self.RCV_SAV_FILE.setObjectName("RCV_SAV_FILE")
        self.horizontalLayout_5.addWidget(self.RCV_SAV_FILE)
        self.RCV_CUT_FORMAT = QtWidgets.QCheckBox(self.groupBox_2)
        self.RCV_CUT_FORMAT.setObjectName("RCV_CUT_FORMAT")
        self.horizontalLayout_5.addWidget(self.RCV_CUT_FORMAT)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SND_MODE_ASCII = QtWidgets.QRadioButton(self.groupBox_3)
        self.SND_MODE_ASCII.setObjectName("SND_MODE_ASCII")
        self.horizontalLayout_8.addWidget(self.SND_MODE_ASCII)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.SND_MODE_HEX = QtWidgets.QRadioButton(self.groupBox_3)
        self.SND_MODE_HEX.setObjectName("SND_MODE_HEX")
        self.horizontalLayout_8.addWidget(self.SND_MODE_HEX)
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.SND_TRS_TOKEN = QtWidgets.QCheckBox(self.groupBox_3)
        self.SND_TRS_TOKEN.setObjectName("SND_TRS_TOKEN")
        self.horizontalLayout_8.addWidget(self.SND_TRS_TOKEN)
        self.SND_AUTO_ENTER = QtWidgets.QCheckBox(self.groupBox_3)
        self.SND_AUTO_ENTER.setObjectName("SND_AUTO_ENTER")
        self.horizontalLayout_8.addWidget(self.SND_AUTO_ENTER)
        self.SND_ATT_BIT = QtWidgets.QCheckBox(self.groupBox_3)
        self.SND_ATT_BIT.setObjectName("SND_ATT_BIT")
        self.horizontalLayout_8.addWidget(self.SND_ATT_BIT)
        self.SND_FORMAT = QtWidgets.QCheckBox(self.groupBox_3)
        self.SND_FORMAT.setObjectName("SND_FORMAT")
        self.horizontalLayout_8.addWidget(self.SND_FORMAT)
        self.SND_CIRCLE = QtWidgets.QCheckBox(self.groupBox_3)
        self.SND_CIRCLE.setObjectName("SND_CIRCLE")
        self.horizontalLayout_8.addWidget(self.SND_CIRCLE)
        self.SND_CIRCLE_INT = QtWidgets.QSpinBox(self.groupBox_3)
        self.SND_CIRCLE_INT.setObjectName("SND_CIRCLE_INT")
        self.horizontalLayout_8.addWidget(self.SND_CIRCLE_INT)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.openFileBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.openFileBtn.setObjectName("openFileBtn")
        self.horizontalLayout_8.addWidget(self.openFileBtn)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_11.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_10.setSpacing(11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sendCmdInputTextEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.sendCmdInputTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendCmdInputTextEdit.setObjectName("sendCmdInputTextEdit")
        self.horizontalLayout_10.addWidget(self.sendCmdInputTextEdit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.sendCmdBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.sendCmdBtn.setObjectName("sendCmdBtn")
        self.verticalLayout_2.addWidget(self.sendCmdBtn)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.DF_LENGTH_MODE_FIXED = QtWidgets.QRadioButton(self.groupBox_6)
        self.DF_LENGTH_MODE_FIXED.setObjectName("DF_LENGTH_MODE_FIXED")
        self.horizontalLayout_12.addWidget(self.DF_LENGTH_MODE_FIXED)
        self.DF_LENGTH = QtWidgets.QSpinBox(self.groupBox_6)
        self.DF_LENGTH.setObjectName("DF_LENGTH")
        self.horizontalLayout_12.addWidget(self.DF_LENGTH)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.DF_LENGTH_MODE_VARIABLE = QtWidgets.QRadioButton(self.groupBox_6)
        self.DF_LENGTH_MODE_VARIABLE.setObjectName("DF_LENGTH_MODE_VARIABLE")
        self.horizontalLayout_12.addWidget(self.DF_LENGTH_MODE_VARIABLE)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.DF_START_BIT = QtWidgets.QLineEdit(self.groupBox_6)
        self.DF_START_BIT.setMinimumSize(QtCore.QSize(200, 0))
        self.DF_START_BIT.setObjectName("DF_START_BIT")
        self.horizontalLayout_12.addWidget(self.DF_START_BIT)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.DF_END_BIT = QtWidgets.QLineEdit(self.groupBox_6)
        self.DF_END_BIT.setMinimumSize(QtCore.QSize(200, 0))
        self.DF_END_BIT.setObjectName("DF_END_BIT")
        self.horizontalLayout_12.addWidget(self.DF_END_BIT)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.DF_WITH_CRC = QtWidgets.QCheckBox(self.groupBox_6)
        self.DF_WITH_CRC.setObjectName("DF_WITH_CRC")
        self.horizontalLayout_12.addWidget(self.DF_WITH_CRC)
        self.CRC_MODES = QtWidgets.QComboBox(self.groupBox_6)
        self.CRC_MODES.setObjectName("CRC_MODES")
        self.horizontalLayout_12.addWidget(self.CRC_MODES)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addWidget(self.groupBox_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口调试工具 Coding By Lex"))
        self.groupBox_5.setTitle(_translate("MainWindow", "串口选择及设定："))
        self.label_6.setText(_translate("MainWindow", "串口号："))
        self.refreshComPorts.setText(_translate("MainWindow", "刷新"))
        self.label_5.setText(_translate("MainWindow", "  波特率："))
        self.label_4.setText(_translate("MainWindow", "  校验位："))
        self.label_3.setText(_translate("MainWindow", "  数据位："))
        self.label_2.setText(_translate("MainWindow", "  停止位："))
        self.label.setText(_translate("MainWindow", "  流控制："))
        self.openComPortBtn.setText(_translate("MainWindow", "打开串口"))
        self.groupBox.setTitle(_translate("MainWindow", "数据日志:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收格式设定："))
        self.RCV_MODE_ASCII.setText(_translate("MainWindow", "ASCII"))
        self.RCV_MODE_HEX.setText(_translate("MainWindow", "HEX"))
        self.RCV_CHG_LINE.setText(_translate("MainWindow", "日志自动换行  "))
        self.RCV_OFF_DISPLAY.setText(_translate("MainWindow", "接收数据不显示  "))
        self.RCV_SAV_FILE.setText(_translate("MainWindow", "接收保存到文件"))
        self.RCV_CUT_FORMAT.setText(_translate("MainWindow", "按数据帧格式截断"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送格式设定："))
        self.SND_MODE_ASCII.setText(_translate("MainWindow", "ASCII"))
        self.SND_MODE_HEX.setText(_translate("MainWindow", "HEX"))
        self.SND_TRS_TOKEN.setText(_translate("MainWindow", "自动解析转义符  "))
        self.SND_AUTO_ENTER.setText(_translate("MainWindow", "AT 指令自动回车  "))
        self.SND_ATT_BIT.setText(_translate("MainWindow", "自动发送附加位"))
        self.SND_FORMAT.setText(_translate("MainWindow", "按数据帧格式发送"))
        self.SND_CIRCLE.setText(_translate("MainWindow", "循环"))
        self.label_7.setText(_translate("MainWindow", "ms"))
        self.openFileBtn.setText(_translate("MainWindow", "打开文件"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据发送："))
        self.sendCmdBtn.setText(_translate("MainWindow", "发送"))
        self.groupBox_6.setTitle(_translate("MainWindow", "数据帧格式设定："))
        self.DF_LENGTH_MODE_FIXED.setText(_translate("MainWindow", "定长  "))
        self.label_9.setText(_translate("MainWindow", "字节  "))
        self.DF_LENGTH_MODE_VARIABLE.setText(_translate("MainWindow", "不定长"))
        self.label_10.setText(_translate("MainWindow", " 数据帧起始位："))
        self.label_11.setText(_translate("MainWindow", "  数据帧结束位："))
        self.DF_WITH_CRC.setText(_translate("MainWindow", "带校验"))
