# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lex Chen\Desktop\datafram_test\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comPortListComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comPortListComboBox.setObjectName("comPortListComboBox")
        self.horizontalLayout_3.addWidget(self.comPortListComboBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.baudrateComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.baudrateComboBox.setEditable(True)
        self.baudrateComboBox.setObjectName("baudrateComboBox")
        self.horizontalLayout_3.addWidget(self.baudrateComboBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verifyBitComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.verifyBitComboBox.setObjectName("verifyBitComboBox")
        self.horizontalLayout_3.addWidget(self.verifyBitComboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dataBitComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.dataBitComboBox.setObjectName("dataBitComboBox")
        self.horizontalLayout_3.addWidget(self.dataBitComboBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.stopBitComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.stopBitComboBox.setObjectName("stopBitComboBox")
        self.horizontalLayout_3.addWidget(self.stopBitComboBox)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.flowControlComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.flowControlComboBox.setObjectName("flowControlComboBox")
        self.horizontalLayout_3.addWidget(self.flowControlComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.openComPortBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.openComPortBtn.setObjectName("openComPortBtn")
        self.horizontalLayout_3.addWidget(self.openComPortBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.logTextEdit.setObjectName("logTextEdit")
        self.horizontalLayout_4.addWidget(self.logTextEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.receiveASCIIRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.receiveASCIIRadio.setObjectName("receiveASCIIRadio")
        self.horizontalLayout_5.addWidget(self.receiveASCIIRadio)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.receiveHexRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.receiveHexRadio.setObjectName("receiveHexRadio")
        self.horizontalLayout_5.addWidget(self.receiveHexRadio)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.autoChangeLineCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.autoChangeLineCheckBox.setObjectName("autoChangeLineCheckBox")
        self.horizontalLayout_5.addWidget(self.autoChangeLineCheckBox)
        self.noDisplayLogCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.noDisplayLogCheckBox.setObjectName("noDisplayLogCheckBox")
        self.horizontalLayout_5.addWidget(self.noDisplayLogCheckBox)
        self.receiveToFileCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.receiveToFileCheckBox.setObjectName("receiveToFileCheckBox")
        self.horizontalLayout_5.addWidget(self.receiveToFileCheckBox)
        self.cutByDataFrameCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.cutByDataFrameCheckBox.setObjectName("cutByDataFrameCheckBox")
        self.horizontalLayout_5.addWidget(self.cutByDataFrameCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sendASCIIRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.sendASCIIRadio.setObjectName("sendASCIIRadio")
        self.horizontalLayout_8.addWidget(self.sendASCIIRadio)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.sendHexRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.sendHexRadio.setObjectName("sendHexRadio")
        self.horizontalLayout_8.addWidget(self.sendHexRadio)
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.autoTransferTokenCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.autoTransferTokenCheckBox.setObjectName("autoTransferTokenCheckBox")
        self.horizontalLayout_8.addWidget(self.autoTransferTokenCheckBox)
        self.cmdATautoEnterCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.cmdATautoEnterCheckBox.setObjectName("cmdATautoEnterCheckBox")
        self.horizontalLayout_8.addWidget(self.cmdATautoEnterCheckBox)
        self.sendAttachBitCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.sendAttachBitCheckBox.setObjectName("sendAttachBitCheckBox")
        self.horizontalLayout_8.addWidget(self.sendAttachBitCheckBox)
        self.sendByDataFrameCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.sendByDataFrameCheckBox.setObjectName("sendByDataFrameCheckBox")
        self.horizontalLayout_8.addWidget(self.sendByDataFrameCheckBox)
        self.circleSendCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.circleSendCheckBox.setObjectName("circleSendCheckBox")
        self.horizontalLayout_8.addWidget(self.circleSendCheckBox)
        self.circleIntervalSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.circleIntervalSpinBox.setObjectName("circleIntervalSpinBox")
        self.horizontalLayout_8.addWidget(self.circleIntervalSpinBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.openFileBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.openFileBtn.setObjectName("openFileBtn")
        self.horizontalLayout_8.addWidget(self.openFileBtn)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_11.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_10.setSpacing(11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sendCmdInputTextEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.sendCmdInputTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendCmdInputTextEdit.setObjectName("sendCmdInputTextEdit")
        self.horizontalLayout_10.addWidget(self.sendCmdInputTextEdit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.sendCmdBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.sendCmdBtn.setObjectName("sendCmdBtn")
        self.verticalLayout_2.addWidget(self.sendCmdBtn)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.dataFrameFixedLengthCheckBox = QtWidgets.QRadioButton(self.groupBox_6)
        self.dataFrameFixedLengthCheckBox.setObjectName("dataFrameFixedLengthCheckBox")
        self.horizontalLayout_12.addWidget(self.dataFrameFixedLengthCheckBox)
        self.dataFrameFixLengthSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.dataFrameFixLengthSpinBox.setObjectName("dataFrameFixLengthSpinBox")
        self.horizontalLayout_12.addWidget(self.dataFrameFixLengthSpinBox)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.variableDataFrameLengthCheckBox = QtWidgets.QRadioButton(self.groupBox_6)
        self.variableDataFrameLengthCheckBox.setObjectName("variableDataFrameLengthCheckBox")
        self.horizontalLayout_12.addWidget(self.variableDataFrameLengthCheckBox)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.dataFrameStartBitTextEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.dataFrameStartBitTextEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.dataFrameStartBitTextEdit.setObjectName("dataFrameStartBitTextEdit")
        self.horizontalLayout_12.addWidget(self.dataFrameStartBitTextEdit)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.dataFrameEndBitTextEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.dataFrameEndBitTextEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.dataFrameEndBitTextEdit.setObjectName("dataFrameEndBitTextEdit")
        self.horizontalLayout_12.addWidget(self.dataFrameEndBitTextEdit)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.isCrcCheckBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.isCrcCheckBox.setObjectName("isCrcCheckBox")
        self.horizontalLayout_12.addWidget(self.isCrcCheckBox)
        self.crcTypeComboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.crcTypeComboBox.setObjectName("crcTypeComboBox")
        self.horizontalLayout_12.addWidget(self.crcTypeComboBox)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addWidget(self.groupBox_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口调试工具 Coding by lex"))
        self.groupBox_5.setTitle(_translate("MainWindow", "串口选择及设定："))
        self.label_6.setText(_translate("MainWindow", "串口号："))
        self.label_5.setText(_translate("MainWindow", "  波特率："))
        self.label_4.setText(_translate("MainWindow", "  校验位："))
        self.label_3.setText(_translate("MainWindow", "  数据位："))
        self.label_2.setText(_translate("MainWindow", "  停止位："))
        self.label.setText(_translate("MainWindow", "  流控制："))
        self.openComPortBtn.setText(_translate("MainWindow", "打开串口"))
        self.groupBox.setTitle(_translate("MainWindow", "数据日志:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收格式设定："))
        self.receiveASCIIRadio.setText(_translate("MainWindow", "ASCII"))
        self.receiveHexRadio.setText(_translate("MainWindow", "HEX"))
        self.autoChangeLineCheckBox.setText(_translate("MainWindow", "日志自动换行  "))
        self.noDisplayLogCheckBox.setText(_translate("MainWindow", "接收数据不显示  "))
        self.receiveToFileCheckBox.setText(_translate("MainWindow", "接收保存到文件"))
        self.cutByDataFrameCheckBox.setText(_translate("MainWindow", "按数据帧格式截断"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送格式设定："))
        self.sendASCIIRadio.setText(_translate("MainWindow", "ASCII"))
        self.sendHexRadio.setText(_translate("MainWindow", "HEX"))
        self.autoTransferTokenCheckBox.setText(_translate("MainWindow", "自动解析转义符  "))
        self.cmdATautoEnterCheckBox.setText(_translate("MainWindow", "AT 指令自动回车  "))
        self.sendAttachBitCheckBox.setText(_translate("MainWindow", "自动发送附加位"))
        self.sendByDataFrameCheckBox.setText(_translate("MainWindow", "按数据帧格式发送"))
        self.circleSendCheckBox.setText(_translate("MainWindow", "循环"))
        self.label_7.setText(_translate("MainWindow", "ms"))
        self.openFileBtn.setText(_translate("MainWindow", "打开文件"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据发送："))
        self.sendCmdBtn.setText(_translate("MainWindow", "发送"))
        self.groupBox_6.setTitle(_translate("MainWindow", "数据帧格式设定："))
        self.dataFrameFixedLengthCheckBox.setText(_translate("MainWindow", "定长  "))
        self.label_9.setText(_translate("MainWindow", "字节  "))
        self.variableDataFrameLengthCheckBox.setText(_translate("MainWindow", "不定长"))
        self.label_10.setText(_translate("MainWindow", " 数据帧起始位："))
        self.label_11.setText(_translate("MainWindow", "  数据帧结束位："))
        self.isCrcCheckBox.setText(_translate("MainWindow", "带校验"))
